package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"fmt"

	"github.com/soupersoul/connections/graph/model"
)

// ListPerson is the resolver for the listPerson field.
func (r *queryResolver) ListPerson(ctx context.Context, input *model.ListInput) ([]*model.Person, error) {
	panic(fmt.Errorf("not implemented: ListPerson - listPerson"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

type mutationResolver struct{ *Resolver }
