// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ListInput struct {
	Name *string `json:"name,omitempty"`
}

type Person struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Address    *string `json:"address,omitempty"`
	Zipcode    *string `json:"zipcode,omitempty"`
	Mobile     *string `json:"mobile,omitempty"`
	Tel        *string `json:"tel,omitempty"`
	Fax        *string `json:"fax,omitempty"`
	Email      *string `json:"email,omitempty"`
	HomePage   *string `json:"homePage,omitempty"`
	Company    *string `json:"company,omitempty"`
	Department *string `json:"department,omitempty"`
	Position   *string `json:"position,omitempty"`
	Title      *string `json:"title,omitempty"`
	StockCode  *string `json:"stockCode,omitempty"`
	Hotline    *string `json:"hotline,omitempty"`
	Qq         *string `json:"qq,omitempty"`
	Wechat     *string `json:"wechat,omitempty"`
	Blog       *string `json:"blog,omitempty"`
	CertNum    *string `json:"certNum,omitempty"`
}
